version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"

  gitea:
    build:
      context: .
      dockerfile: Dockerfile.gitea
    ports:
      - "3000:3000"
      - "2222:22"
